#!/bin/bash
USERID=$(id -u)
#echo "User id is: $USERID"
if [ $USERID -ne 0 ]
then
    echo "Please run this script with root priveleges"
    exit 1

fi
dnf list install git 
if[ $? -ne 0 ]
then
    echo "Git is not installed , got install it..."
    dnf install git -y
else
    echo "git already installed , nothign to do"
fi