#!/bin/bash

USERID=$(id -u)

if [ "$USERID" -ne 0 ]; then
    echo "Please run this script with root privileges"
    exit 1
fi

# Check if Git is installed
dnf list installed git &>/dev/null
if [ $? -ne 0 ]; then
    echo "Git is not installed. Installing..."
    dnf install git -y
    if [ $? -ne 0 ]; then
        echo "Git installation failed. Please check the command."
        exit 1
    else
        echo "Git installed successfully."
    fi
else
    echo "Git is already installed. Nothing to do."
fi

# Check if MySQL is installed
dnf list installed mysql &>/dev/null
if [ $? -ne 0 ]; then
    echo "MySQL is not installed. Installing..."
    dnf install mysql -y
    if [ $? -ne 0 ]; then
        echo "MySQL installation failed. Please check."
        exit 1
    else
        echo "MySQL installed successfully."
    fi
else
    echo "MySQL is already installed. Nothing to do."
fi
